(function(g){var window=this;'use strict';var e4a=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},f4a=function(a){return g.uG(a)&&!a.N("web_player_i_see_captions_3_killswitch")},g4a=function(a,b){var c=new g.QG;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},h4a=function(a,b){var c,d,e;
return g.A(function(f){if(1==f.j)return c=a+"|"+b,g.x(f,g.Mw(),2);if(3!=f.j){d=f.u;if(!d)throw g.lw("gct");return g.x(f,g.BH(d),3)}e=f.u;return f.return(e.get("captions",c))})},i4a=function(a,b,c){h4a(a,b).then(function(d){d&&c(d.trackData,new g.QG(d.metadata))})},l4a=function(a){if(!j4a.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(k4a,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},q5=function(){this.segments=[]},m4a=function(a,b){var c=g.pc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.$b(a.segments,c),g.$b(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.lc(a.segments,c,0,b),g.lc(a.segments,c+1,0,b)))},n4a=function(a,b,c,d,e,f){g.L.call(this);
this.policy=a;this.player=b;this.ea=c;this.S=d;this.F=e;this.Z=f;this.Y=this.player.V();this.C=new q5;this.I=-1;this.B=this.u=this.j=null;this.J=new g.fo(this.iR,1E3,this);this.events=new g.cE(this);g.N(this,this.J);g.N(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.Uw);this.Uw();this.iR()},o4a=function(a){return a.j&&a.j.B?a.j.B+a.player.Bd()<a.player.getCurrentTime():!1},p4a=function(a,b){var c=g.vD(b,a.policy,{}).Ce(),d={format:"RAW",
withCredentials:!0};a.policy.La&&(d.method="POST",d.postBody=b.Vs()||(0,g.xV)([120,0]));a.F&&(d.responseType="arraybuffer");a.B=g.Qu(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.F?e.response:e.responseText)||400<=e.status,h=g.Oxa(e);if(h){e=g.vD(a.u,a.policy,{});a.u.Ik(e,h);p4a(a,a.u);break a}f?a.player.va("capfail",{status:e.status}):(a.player.Wi().Ah("fcb_r"),h=a.u.j[0].Ma,null!=a.S&&a.I!==h&&(f=a.u.j[0],a.F?a.S(e.response,1E3*(f.startTime+a.player.Bd())):a.S(e.responseText,
1E3*(f.startTime+a.player.Bd())),a.I=h))}a.u=null;a.B=null}}).rj(function(e){a.u=null;
a.B=null;var f;a.player.va("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;m4a(a.C,a.u.j[0].Ma)},r5=function(a,b){g.BO.call(this,b.V());
this.u=a;this.G=b;this.B=null;this.F=!1;this.I=g.wG(this.G.V())&&!this.u.isManifestless},r4a=function(a,b){var c=[],d;
for(d in a.u.j)if(a.u.j.hasOwnProperty(d)){var e=a.u.j[d];if(g.EO(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.f2a.get(e);null==n&&(n=q4a[e]||q4a[e.replace(/-/g,"_")],g.f2a.set(e,n));h=n||h}c.push(new g.QG({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},s4a=function(a,b){return null!=b&&b in a.u.j?a.u.j[b]:null},t4a=function(a,b,c){var d=
[],e;
for(e in a.u.j)if(a.u.j.hasOwnProperty(e)){var f=a.u.j[e];if(g.EO(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},s5=function(a,b,c,d,e,f,h,l){var m={};
Object.assign(m,b);Object.assign(m,a.params);Object.assign(m,c);var n={};Object.assign(n,b.Zd);a.params.Zd&&Object.assign(n,a.params.Zd);Object.assign(n,c.Zd);m.Zd=n;g.X.call(this,{D:"div",K:"caption-window",X:{id:"caption-window-"+a.id,dir:1===m.yh?"rtl":"ltr",tabindex:"0",lang:m.lang},W:[{D:"span",K:"captions-text",X:{style:"word-wrap: normal; display: block;"}}]});this.F=[];this.Ba=!1;this.u=a;this.La=this.Ia=null;this.playerWidth=f;this.playerHeight=h;this.I=null;this.maxWidth=.96*f;this.Xa=.96*
h;this.j=m;this.Ob=c;this.ea=b;this.C=this.Ca("captions-text");this.Cb=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.oa=e/360*16;!l.jb("web_player_scale_font_size_for_shorts_killswitch")&&e>=d&&(this.oa=f/640*16);this.type=0;this.bb=this.oa*u4a(n);a=new g.gz(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.wV,this);a.subscribe("dragmove",this.vV,this);a.subscribe("dragend",this.uV,this);this.kb=this.ib=
0;b="";this.j.windowOpacity&&(a=l4a(this.j.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");a={"background-color":b,display:!1===this.j.isVisible?"none":"","text-align":v4a[this.j.textAlign]};this.Cb&&(a["border-radius"]=b?this.bb/8+"px":"");if(this.B=2===this.u.params.yh||3===this.u.params.yh)b=this.element,c="vertical-rl",1===this.j.VL&&(c="vertical-lr"),g.Fc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Gl(b,"-o-writing-mode",c),g.Gl(b,"-webkit-writing-mode",c),g.Gl(b,"writing-mode",
c),g.Gl(b,"text-orientation","upright"),g.no(b,"ytp-vertical-caption"),3===this.u.params.yh&&(g.Gl(b,"text-orientation",""),g.Gl(b,"transform","rotate(180deg)"));g.Gl(this.element,a);switch(this.j.zk){case 0:case 1:case 2:g.no(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.no(this.element,"ytp-caption-window-bottom")}},u4a=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},w4a=function(a,b){var c={},d=b.background?b.background:a.j.Zd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Zd.backgroundOpacity;d=l4a(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Cb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.bb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.oa*u4a(b)+"px";d=1;e=b.color||a.j.Zd.color;if(b.color||null!=b.textOpacity)e=l4a(e),d=null==b.textOpacity?a.j.Zd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.yH&&(h=e=b.yH);var l=a.oa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.av()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Zd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.T_&&(c.visibility="hidden");1===b.EQ&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.AG||g.jw,3===a.u.params.yh?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Vl||2===b.Vl||3===b.Vl||4===b.Vl||5===b.Vl)if(g.AG)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Vl){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},x4a=function(a){a.I=g.ph("SPAN");
g.Gl(a.I,{display:"block"});g.no(a.I,"caption-visual-line");a.C.appendChild(a.I)},y4a=function(a,b){var c=g.ph("SPAN");
g.Gl(c,{display:"inline-block","white-space":"pre-wrap"});g.Gl(c,w4a(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.Gl(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Gl(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},z4a=function(a,b,c){a.Ba=a.Ba||!!c;
var d={};Object.assign(d,a.j.Zd);Object.assign(d,c||b.j);Object.assign(d,a.Ob.Zd);(c=!a.I)&&x4a(a);for(var e=a.Ia&&a.La&&g.Gf(d,a.La)?a.Ia:y4a(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(x4a(a),e=y4a(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.qh(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.AG||!g.Il(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Il(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.mf?g.Gl(e,m,"1em"):g.Gl(e,m,"0.5em")))}a.La=d;a.Ia=e;a.F.push(b)},t5=function(a,b,c,d){g.BO.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ta=d;this.C=b.wH},u5=function(a,b,c,d,e,f,h,l){s5.call(this,a,b,c,d,e,f,h,l);
this.type=1},v5=function(a,b,c,d,e,f,h,l){s5.call(this,a,b,c,d,e,f,h,l);
this.type=2;this.J=[];this.Z=this.S=this.Pa=0;this.Aa=NaN;this.ub=0;this.Nb=null;this.Ua=new g.fo(this.N3,433,this);g.no(this.element,"ytp-caption-window-rollup");g.N(this,this.Ua);g.Gl(this.element,"overflow","hidden")},A4a=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.VL&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},B4a=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.gp,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.S=d;b=Math;c=b.max;isNaN(a.Aa)&&((d=a.j.Sp)?(e=g.ph("SPAN"),g.wh(e,"\u2013".repeat(d)),g.Gl(e,w4a(a,a.j.Zd)),a.C.appendChild(e),a.Aa=e.offsetWidth,a.C.removeChild(e)):a.Aa=0);d=a.C;a.Z=c.call(b,a.Aa,a.ub,(a.B?d.offsetHeight:d.offsetWidth)+1)},C4a=function(a,b){B4a(a);
var c=a.J.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.S-c;if(c!==a.Pa){var d=0<c&&0===a.Pa;b||isNaN(c)||d||(g.no(a.element,"ytp-rollup-mode"),g.go(a.Ua));g.Gl(a.C,"transform",A4a(a,c));a.Pa=c}B4a(a)},w5=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.qA.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},x5=function(a,b,c,d,e){g.qA.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},D4a=function(a){var b="_"+y5++;
return new x5(0,0x8000000000000,0,b,a)},F4a=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.nf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=E4a(l.textContent,n.textContent,p.textContent,f.textContent,h);return new w5(a,b,e,c,l,d,m)}switch(m.nf){case 9:case 10:m.Vl=1;break;case 11:m.Vl=2;break;case 12:m.Vl=3;break;case 13:m.Vl=4;break;case 14:m.Vl=5}return new w5(a,b,e,c,l.textContent||"",d,m)},E4a=function(a,b,c,d,e){var f=g.av(),h=
f?g.ph("DIV"):g.ph("RUBY"),l=g.ph("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.ph("DIV"):g.ph("RP");a.textContent=b;h.appendChild(a);b=f?g.ph("DIV"):g.ph("RT");b.textContent=c;h.appendChild(b);c=e.nf;if(10===c||11===c||12===c||13===c||14===c)if(g.Gl(b,"text-emphasis-style","filled circle"),g.Gl(b,"text-emphasis-color","currentcolor"),g.Gl(b,"webkit-text-emphasis","filled circle"),11===e.nf||13===e.nf)g.Gl(b,"webkit-text-emphasis-position","under left"),g.Gl(b,"text-emphasis-position","under left");c=!0;if(4===e.nf||7===e.nf||12===e.nf||
14===e.nf)g.Gl(h,"ruby-position","over"),g.Gl(h,"-webkit-ruby-position","before");else if(5===e.nf||6===e.nf||11===e.nf||13===e.nf)g.Gl(h,"ruby-position","under"),g.Gl(h,"-webkit-ruby-position","after"),c=!1;e=f?g.ph("DIV"):g.ph("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Gl(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Gl(f,"display","none"),f=f.nextElementSibling,g.Gl(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Gl(h.lastElementChild,"display","none"),d?(g.Gl(h,"padding-top","0.6em"),g.Gl(f,"top","0")):(g.Gl(h,"padding-bottom","0.6em"),g.Gl(f,"bottom","0")));return h},z5=function(){g.L.apply(this,arguments)},A5=function(a){z5.call(this);
this.C=a;this.pens={};this.S={};this.Z={};this.F="_"+y5++;this.J={};this.B=this.j=null;this.I=!0},B5=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},C5=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},D5=function(a,b){a=B5(a,b);
return void 0!==a?a:null},F5=function(a,b){a=a.getAttribute(b);
if(null!=a)return E5.test(a),a},G4a=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=D5(b,"mh");null!=a&&(c.Rw=a);a=D5(b,"ju");null!=a&&(c.textAlign=a);a=D5(b,"pd");null!=a&&(c.yh=a);a=D5(b,"sd");null!=a&&(c.VL=a);a=F5(b,"wfc");null!=a&&(c.windowColor=a);b=B5(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},H4a=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.S[d]);a=D5(b,"ap");null!=a&&(c.zk=a);a=B5(b,"cc");null!=a&&(c.Sp=a);a=B5(b,"ah");null!=a&&(c.gj=a);a=B5(b,"rc");null!=a&&(c.gp=a);b=B5(b,"av");null!=b&&(c.Wl=b);return c},I4a=function(a,b,c,d){var e={};
Object.assign(e,H4a(a,b));Object.assign(e,G4a(a,b));d?g.Gf(e,a.C)?(d=a.F,e=a.C):d="_"+y5++:d=b.getAttribute("id")||"_"+y5++;a=B5(b,"t")+c;b=B5(b,"d")||0x8000000000000;if(2===e.yh||3===e.yh)c=e.gp,e.gp=e.Sp,e.Sp=c;return new x5(a,b,0,d,e)},G5=function(a){z5.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.F=new Map;this.B=new Map},H5=function(a){a=g.Ng(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},J4a=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.F.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.gp=a);b=b.ccColCount;void 0!==b&&(f.Sp=b);if(2===f.yh||3===f.yh)b=f.gp,f.gp=f.Sp,f.Sp=b;return new x5(c,d,0,e,f)},L4a=function(){this.B=this.time=this.mode=this.u=0;
this.C=new K4a(this);this.F=new K4a(this);this.j=[];this.clear()},N4a=function(a,b,c){if(255===a&&255===b||!a&&!b)return{rs:a,
Op:b,result:0};a=M4a[a];b=M4a[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Op===d;if(d)return{rs:a,Op:b,result:1}}else if(b&128&&1<=a&&31>=a)return{rs:a,Op:b,result:2};return{rs:a,Op:b,result:3}},P4a=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.F.u.clear()):(a.B=0,O4a(a.C,b,c,d))},Q4a=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.t(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?P4a(a,d.aP,d.bP,b):1===d.type&&a.u&496&&O4a(a.F,d.aP,d.bP,b);a.j.length=0},I5=function(){this.type=0},J5=function(){this.state=this.Op=this.rs=0},R4a=function(){this.timestamp=this.j=0},K5=function(a){this.F=a;
this.B=[];this.j=this.u=this.row=0;this.style=new I5;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new R4a}},L5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.F.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.F.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},W4a=function(a,b){switch(a){case 0:return S4a[(b&127)-32];
case 1:return T4a[b&15];case 2:return U4a[b&31];case 3:return V4a[b&31]}return 0},M5=function(a){return a.B[a.row][a.u]},N5=function(a,b,c){2<=b&&1<a.u&&(--a.u,M5(a).j=0);
var d=M5(a);d.timestamp=a.F.time+0;d.j=W4a(b,c);32>a.u&&a.u++},X4a=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},O5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Y4a=function(a){a.row=0<a.j?a.j:1;
a.u=1;O5(a,0,15)},Z4a=function(a){this.B=a;
this.F=0;this.style=new I5;this.I=new K5(this.B);this.J=new K5(this.B);this.text=new K5(this.B);this.u=this.I;this.C=this.J;this.j=this.u},$4a=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(L5(d,c),Y4a(a.u),Y4a(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(L5(d,c),O5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},a5a=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},b5a=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},K4a=function(a){this.j=a;
this.F=0;this.B=new Z4a(this.j);this.I=new Z4a(this.j);this.u=new J5;this.C=this.B},O4a=function(a,b,c,d){a.u.update();
b=N4a(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.rs;c=b.Op;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&N5(a,0,b),c&96&&N5(a,0,c),0!==b&&0!==c&&3===a.style.type&&L5(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.rs=e,b.Op=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.F<<2)+(b.F<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.F<<2)+(b.F<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;X4a(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));O5(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:N5(b.j,0,32);break a;case 48:57===c?(d=b.j,M5(d).j=0,32>d.u&&d.u++):N5(b.j,1,c&15)}break;case 2:c&32&&N5(b.j,2,c&31);break;case 3:c&32&&N5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:a5a(b);
break;case 33:d=b.j;1<d.u&&(--d.u,M5(d).j=0);break;case 36:d=b.j;b=M5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:$4a(b,2,d);break;case 38:$4a(b,3,d);break;case 39:$4a(b,4,d);break;case 40:N5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Y4a(d);b5a(b);break;case 43:b5a(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:L5(a,d)}O5(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;L5(a,d);X4a(a,b,b+1,a.j-1);O5(a,a.row,1)}break;case 46:O5(b.C,0,15);break;case 47:L5(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,a5a(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},c5a=function(){},P5=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.F=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},Q5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},R5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},S5=function(a,b){z5.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new L4a;this.j.u=1<<this.track},e5a=function(a){if("string"===typeof a)return!1;
a=new P5(a,8,0);return d5a(a)},d5a=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==R5(a))return!1;
a.version=Q5(a);if(1<a.version)return!1;Q5(a);Q5(a);Q5(a);return!0},T5=function(){z5.call(this)},f5a=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new w5(b,c,d,e.id,p.nodeValue,f||0<n,g.Df(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);f5a(a,b,c,d,e,!0,p,q,m)}}},g5a=function(a){var b=a.split(":");
a=0;b=g.t(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},h5a=function(a,b,c,d){d=Object.assign({Rw:0},d);
return new x5(a,b,c,"_"+y5++,d)},U5=function(a,b){g.L.call(this);
this.G=a;this.Y=b;this.parser=null;this.j=this.G.uw()},n5a=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=i5a(a,b,d),l=[];try{for(var m=g.t(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,r=p.LL;l="string"!==typeof q?l.concat(j5a(a,c,q,r,f)):"WEBVTT"===q.substring(0,6)?l.concat(k5a(a,q,r)):l.concat(l5a(a,c,q,r))}var w=l}catch(y){g.qz(y),a.clear(),w=[]}if(0!==w.length)return w}b=m5a(b);if(!b)return[];try{return"string"!==typeof b?j5a(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?k5a(a,b,d):l5a(a,c,b,d)}catch(y){return g.qz(y),a.clear(),[]}},m5a=function(a){if("string"===
typeof a||e5a(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.vC(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.eC(a)},i5a=function(a,b,c){if("string"===typeof b||e5a(b))return[{trackData:b,
LL:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.Cwa(d);if(a.j&&e){var f=g.uwa(e),h=g.vwa(e);e=e.j;f&&e&&a.j.uB(e,f,h)}f=g.EC(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.t(f.entries());for(h=f.next();!h.done;h=f.next())e=g.t(h.value),h=e.next().value,e=e.next().value,e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.eC(e),a.push({trackData:e,LL:c+1E3*h});o5a(d,a,c);return a=a.filter(function(l){return!!l.trackData})},
o5a=function(a,b,c){var d=g.vC(a,0,1836476516),e=9E4;
d&&(e=g.wC(d)||9E4);d=0;var f=g.EC(a,1836019558);f=g.t(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.t(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.vC(a,l.dataOffset,1953653094))&&(l=g.vC(a,l.dataOffset,1952867444))&&(l=g.CC(l)/e*1E3,0===h&&(d=l),b[h].LL=l-d+c||c*h*1E3)}},j5a=function(a,b,c,d,e){if(!e5a(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new S5(e,b));return a.parser.u(c,d)},k5a=function(a,b,c){a.parser||(a.parser=new T5);
a=a.parser.u(b,c);.01>Math.random()&&g.rz(Error("Deprecated subtitles format in web player: WebVTT"));return a},l5a=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new G5(p5a(b))),a.parser.u(c,d)}catch(f){return g.qz(f),[]}var e=g.PYa(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new A5(p5a(b),a.Y)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},p5a=function(a){var b=
{};
if(a=g.TG(a))b.lang=a,g.d_a.test(a)&&(b.yh=1);return b},V5=function(a){g.yO.call(this,a);
var b=this;this.G=a;this.Y=this.G.V();this.videoData=this.G.getVideoData();this.kb=this.G.fb();this.B={Zd:{}};this.F={Zd:{}};this.ya=[];this.S={};this.La={};this.ea=!1;this.Ob=g.FI(this.videoData);this.bb=g.GHa(this.videoData,this.G);this.Nb=!!this.videoData.captionTracks.length;this.jc=!!this.videoData.Jd;this.Pa="3"===this.Y.controlsType;this.u=this.I=this.J=this.Ia=this.ib=null;this.Ua=new U5(this.G,this.Y);this.j=null;this.oa=new g.cE(this);this.Xa=new g.X({D:"div",K:"ytp-caption-window-container",
X:{id:"ytp-caption-window-container"}});var c=null,d=g.Wo("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Ko(d));this.storage=c;var e;this.ub=!(null==(e=a.Wd())||!e.lB());this.C=q5a(this);this.Z=!this.C&&this.Pa&&this.ub&&this.bb;g.N(this,this.Ua);this.C?this.Ba=this.Aa=null:(this.Aa=new g.co(this.pM,void 0,this),g.N(this,this.Aa),this.Ba=new g.fo(this.q5,2E3,this),g.N(this,this.Ba));g.N(this,this.oa);this.Y.N("caption_window_container_killswitch")||g.UN(this.player,this.Xa.element,4);
g.N(this,this.Xa);this.C||this.oa.T(a,"resize",this.sM);(this.Cb=(this.Y.N("web_player_track_tag_only_on_fullscreen_for_mweb_killswitch")||g.ZF(this.Y))&&!g.Wy()&&!this.G.isFullscreen()&&!this.C&&!this.Z)&&this.oa.T(a,"resize",this.R2);this.oa.T(a,"onPlaybackAudioChange",this.X1);this.oa.T(a,g.sA("captions"),function(f){b.onCueRangeEnter(f)});
this.oa.T(a,g.tA("captions"),function(f){b.onCueRangeExit(f)});
r5a(this,s5a(this)||{})},w5a=function(a){if(1===a.Y.ib||1===a.videoData.ZI||"alwayson"===g.pI(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.Y.ib){var c;g.yG(a.Y)?c=t5a(a):c=u5a(a,"module-enabled");if(null!=c)return!!c}c=e4a(a.player.getAudioTrack(),f4a(a.Y));var d=g.pI(a.videoData,"yt:cc");if(void 0===v5a(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===g.pI(a.videoData,"yt:cc")},W5=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},v5a=function(a){var b=void 0,c=g.Ev(g.Dv.getInstance(),65);
if(g.yG(a.Y)&&null!=c){if(null!=t5a(a))return!1;b=!c}return b},x5a=function(a){var b;
a.Ob?b=new t5(a.Y,a.videoData,a.player.getAudioTrack(),a.player):a.bb?b=new r5(a.videoData.j,a.player):a.Nb?b=new g.CO(a.Y,a.videoData,a.player.getAudioTrack()):b=new g.FO(a.Y,a.videoData.Jd,a.videoData.videoId,g.cCa(a.videoData),a.videoData.pm);return b},Y5=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.jc?!1:a.Nb?!1:!0);a.Y.N("web_player_should_honor_include_asr_setting")&&g.uG(a.Y)&&(b=b||!!g.Ev(g.Dv.getInstance(),66));b=g.zO(a.u.j,b);for(var c=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.pI(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.TG(b[e])===c[d])return b[e];return a.I&&a.I.B?a.I.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||X5(a)}return null},X5=function(a){return a.I&&a.I.j},Z5=function(a){var b=X5(a);
return!!b&&a.j===b},y5a=function(a){g.zO(a.u.j,!0);
var b=e4a(a.player.getAudioTrack(),f4a(a.Y)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=Y5(a,a.ea):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&W5(a)?c=X5(a):v5a(a)||a.ea||w5a(a)?c=Y5(a,a.ea):W5(a)&&(c=X5(a));if(a.C||a.Z){var d=g.zO(a.u.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.ph("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.RG(f));h.setAttribute("srclang",g.TG(f));h.setAttribute("id",f.toString());a.Z||h.setAttribute("src",a.u.Us(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.G.Wd();c.My(b);c=c.Df();a.ub&&a.oa.T(c.textTracks,"change",a.w4)}else!a.j&&c&&$5(a,c),a.player.Oa("onCaptionsTrackListChanged"),a.player.Oa("onApiChange")},z5a=function(a,b){var c=a.G.Wd().Df().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},$5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ea=c,a.ea&&(g.yG(a.Y)?a6(a,!!b):b6(a,"module-enabled",!!b)));a.j=b;W5(a)&&(a.j=X5(a));a.load()},B5a=function(a,b){if(b instanceof x5){var c=a.S[b.id];
c&&c.u!==b&&(c.dispose(),delete a.S[b.id],c=null);c||(c=A5a(a,b))&&(a.S[b.id]=c)}else c=b.windowId,a.La[c]||(a.La[c]=[]),a.La[c].push(b)},C5a=function(a,b){a.Y.N("caption_window_container_killswitch")?g.UN(a.player,b,4):a.Xa.element.appendChild(b)},A5a=function(a,b){var c=a.kb.getVideoContentRect(!0).height,d=a.kb.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.TG(a.j):null;e&&g.d_a.test(e)&&(b.params.yh=1);e=a.kb.getPlayerSize();a.Y.N("web_player_caption_stickiness_for_glive_killswitch")||"google-live"!==a.Y.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.Rw?b.params.Rw:1<b.j.length?1:0){case 1:return new u5(b,a.B,a.F,d,c,e.width,e.height,a.Y.experiments);case 2:return new v5(b,a.B,a.F,d,c,e.width,e.height,a.Y.experiments);default:return new s5(b,a.B,a.F,d,c,e.width,e.height,a.Y.experiments)}},
r5a=function(a,b,c){c=void 0===c?!1:c;
var d=c6.Zd;a.B={};Object.assign(a.B,c6);a.B.Zd={};Object.assign(a.B.Zd,d);a.F={Zd:{}};var e=b.backgroundOverride?a.F:a.B,f=b.background||d.background;E5.test(f);e.Zd.background=f;e=b.colorOverride?a.F:a.B;f=b.color||d.color;E5.test(f);e.Zd.color=f;e=b.windowColorOverride?a.F:a.B;f=b.windowColor||c6.windowColor;E5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Zd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Zd.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Zd;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.F:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Zd.textOpacity=f;e=b.windowOpacityOverride?a.F:a.B;f=b.windowOpacity;null==f&&(f=c6.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.F:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Zd.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Zd.fontFamily=f;a.loaded&&a.sM();c&&(a.Y.N("web_player_local_storage_for_captions_setting_killswitch")?b6(a,"display-settings",b):g.Nz("yt-player-caption-display-settings",b,2592E3))},E5a=function(a,b,c){b&&!a.J?(b=D4a({yh:0,
lang:"zh-CN"}),a.J=[b,new w5(b.start,b.end-b.start,0,b.id,null!=c?c:"\u5b57\u5e55\u6837\u5f0f\u9884\u89c8")],a.player.me(a.J)):!b&&a.J&&(D5a(a,a.J),a.J=null)},D5a=function(a,b){a.player.uh(b);
b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.cc(a.ya,c.value);g.eo(a.Aa)},u5a=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},b6=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},a6=function(a,b){a.G.isInline()||g.Nz("yt-player-sticky-caption",b,2592E3)},t5a=function(a){if(!a.G.isInline())return g.Oz("yt-player-sticky-caption")},s5a=function(a){return a.Y.N("web_player_local_storage_for_captions_setting_killswitch")?u5a(a,"display-settings"):g.Oz("yt-player-caption-display-settings")},q5a=function(a){var b,c=!(null==(b=a.G.Wd())||!b.kB());
return a.Pa&&c&&!a.bb};
g.dT.prototype.wz=g.ca(39,function(a){var b=2;this.La.has(a)?b=0:g.bLa(this,a)&&(b=1);return b});
g.WV.prototype.wz=g.ca(38,function(a){return this.rd.wz(a)});
g.dT.prototype.uB=g.ca(37,function(a,b,c){this.Ba.set(a,{Is:b,Jy:c})});
g.WV.prototype.uB=g.ca(36,function(a,b,c){this.rd.uB(a,b,c)});
g.TO.prototype.Nv=g.ca(31,function(){for(var a=g.fh(document,"track",void 0,this.j),b=0;b<a.length;b++)g.th(a[b])});
g.OS.prototype.Nv=g.ca(30,function(){this.mediaElement.Nv()});
g.TO.prototype.lB=g.ca(29,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.OS.prototype.lB=g.ca(28,function(){return this.mediaElement.lB()});
g.TO.prototype.kB=g.ca(27,function(){return!!this.j.textTracks});
g.OS.prototype.kB=g.ca(26,function(){return this.mediaElement.kB()});
g.TO.prototype.My=g.ca(25,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.OS.prototype.My=g.ca(24,function(a){this.mediaElement.My(a)});
g.BO.prototype.RK=g.ca(23,function(){return!1});
g.BO.prototype.Iq=g.ca(22,function(){});
g.CO.prototype.Iq=g.ca(21,function(a,b,c){var d=this;this.isDisposed();b=this.Us(a,b);this.xp();this.u=g.Nu(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.FO.prototype.Iq=g.ca(20,function(a,b,c){var d=this;this.isDisposed();b=this.Us(a,b);this.xp();this.u=g.Nu(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.KV.prototype.Jz=g.ca(10,function(){return this.J});
g.pY.prototype.Jz=g.ca(9,function(){var a;return(null==(a=g.IN(this))?void 0:a.uw())||null});
g.NN.prototype.uw=g.ca(8,function(){return this.app.Jz()});
g.QX.prototype.uw=g.ca(7,function(){var a;return(null==(a=this.Ka)?void 0:a.Jz())||null});
g.SB.prototype.qD=g.ca(3,function(a){return(a=this.Sm(a))?a.j:0});
g.JD.prototype.qD=g.ca(2,function(){return 0});
var k4a=/#(.)(.)(.)/,j4a=/^#(?:[0-9a-f]{3}){1,2}$/i,q4a={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgn:"Western Balochi",bho:"Bhojpuri",
bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",
chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",
goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",
ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",
kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",
lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",
mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",
ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};q5.prototype.contains=function(a){a=g.pc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
q5.prototype.length=function(){return this.segments.length/2};
g.v(n4a,g.L);g.k=n4a.prototype;g.k.ra=function(){g.L.prototype.ra.call(this);this.B&&this.B.cancel()};
g.k.Uw=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Bd();var b=this.j;this.j=g.Sb(this.ea.Wm(a).j);b!==this.j&&this.Z&&this.Z()};
g.k.reset=function(){this.C=new q5;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.iR=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Fp(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.By(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)if(b=this.player.uw()){var c=a.j[0].j.info.id,d=a.j[0].Ma,e=a.j[0].C;if(this.policy.La){if(b=b.Vs(e,d,c,3))a.S=b}else if(c=b.Tm(e,d,c,3))if(b=b.wz(d),0===b)c&&(a.B=new g.LB(c));else if(2===b){this.J.start();o4a(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.j[0].duration?(this.C.contains(a.j[0].Ma)||p4a(this,a),this.j=g.Sb(a.j)):!this.Y.N("force_caption_seek_for_live_killswitch")&&o4a(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.v(r5,g.BO);g.k=r5.prototype;g.k.Iq=function(a,b,c){var d=this;this.xp();b=s4a(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?t4a(this,b,"386"):t4a(this,b));if(b){var e=1E3*(b.index.qD(b.index.El())-b.index.getStartTime(b.index.El())),f=new g.DO(this.Y);this.B=new n4a(f,this.G,b,function(h,l){c(h,a,l,e)},this.I||g.HD(b.info),function(){d.B&&d.B.reset();
d.F=!0})}};
g.k.RK=function(){var a=this.F;this.F=!1;return a};
g.k.Nw=function(a){var b=this.I?[new g.QG({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.QG({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?r4a(this,"386"):r4a(this);b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.AO(this.j,c.value);a()};
g.k.xp=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Us=function(){return""};
var E5=/^#(?:[0-9a-f]{3}){1,2}$/i;var v4a=["left","right","center","justify"];g.v(s5,g.X);g.k=s5.prototype;g.k.wV=function(a,b){var c=g.Pl(this.element,this.element.parentElement);this.ib=a-c.x;this.kb=b-c.y;g.no(this.element,"ytp-dragging")};
g.k.vV=function(a,b){var c=g.Rl(this.element);a=a-this.ib-.02*this.playerWidth;var d=b-this.kb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Ng(e,0,2));var f=(d+c.height/2)/this.Xa*3;f=Math.floor(g.Ng(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Ng(a,0,1);c=(d+f/2*c.height)/this.Xa;c=100*g.Ng(c,0,1);this.u.params.zk=b;this.u.params.Wl=c;this.u.params.gj=a;this.u.params.isDefault=!1;this.j.zk=b;this.j.Wl=c;this.j.gj=a;this.j.isDefault=!1;this.ea.zk=b;this.ea.Wl=c;
this.ea.gj=a;this.ea.isDefault=!1;this.gT()};
g.k.uV=function(){g.po(this.element,"ytp-dragging")};
g.k.gT=function(){this.zx(this.F)};
g.k.getType=function(){return this.type};
g.k.zx=function(a){var b=Math.min(this.WP(),this.maxWidth),c=this.VP(),d="";3===this.u.params.yh&&(d="rotate(180deg)");g.Gl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.iH(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.gj+2;d=this.j.zk;switch(d){case 0:case 3:case 6:(b=this.j.Zd.fontSizeIncrement)&&0<b&&2!==this.j.yh&&3!==
this.j.yh&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.j.Wl+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Gl(this.element,
a)};
g.k.iH=function(a){var b;for(b=0;b<a.length&&a[b]===this.F[b];b++);if(this.Ba||this.F.length>b)b=0,this.Ba=!1,this.F=[],this.I=this.La=this.Ia=null,g.rh(this.C);for(;b<a.length;b++)z4a(this,a[b])};
g.k.WP=function(){return 0};
g.k.VP=function(){return 0};
g.k.toString=function(){return g.X.prototype.toString.call(this)};g.v(t5,g.BO);t5.prototype.Iq=function(a,b,c){i4a(this.videoData.videoId,a.vssId,c)};
t5.prototype.Nw=function(a){if(this.audioTrack)for(var b=g.t(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.AO(this.j,c.value);a()};g.v(u5,s5);u5.prototype.iH=function(a){var b=this.u.j;s5.prototype.iH.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,F5a);var e=c.j;var f=d}z4a(this,c,d)}};
var F5a={T_:!0};g.v(v5,s5);g.k=v5.prototype;g.k.gT=function(){g.ho(this.Ua)};
g.k.N3=function(){g.po(this.element,"ytp-rollup-mode");this.zx(this.Nb,!0)};
g.k.VP=function(){return this.B?this.Z:this.S};
g.k.WP=function(){return this.B?this.S:this.Z};
g.k.zx=function(a,b){this.Nb=a;if(this.u.params.gp){for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));this.ub=this.Z;this.S=this.Z=0;s5.prototype.zx.call(this,a);C4a(this,b)}s5.prototype.zx.call(this,a)};g.v(w5,g.qA);w5.prototype.toString=function(){return g.qA.prototype.toString.call(this)};g.v(x5,g.qA);x5.prototype.toString=function(){return g.qA.prototype.toString.call(this)};
var y5=0;g.v(z5,g.L);z5.prototype.u=function(){return[]};
z5.prototype.reset=function(){};g.v(A5,z5);A5.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
A5.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.t(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.t(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=C5(a,"b");
null!=l&&(h.bold=l);l=C5(a,"i");null!=l&&(h.italic=l);l=C5(a,"u");null!=l&&(h.underline=l);l=D5(a,"et");null!=l&&(h.charEdgeStyle=l);l=D5(a,"of");null!=l&&(h.offset=l);l=F5(a,"bc");null!=l&&(h.background=l);l=F5(a,"ec");null!=l&&(h.yH=l);l=F5(a,"fc");null!=l&&(h.color=l);l=D5(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=B5(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=B5(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=B5(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=D5(a,"rb");null!=l&&10!==l&&
0!==l&&(h.nf=10<l?l-1:l);a=D5(a,"hg");null!=a&&(h.EQ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=G4a(this,a);break;case "wp":c=a.getAttribute("id"),this.S[c]=H4a(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.t(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=I4a(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.F;
h=!!C5(a,"a");l=(B5(a,"t")||0)+l;var m=B5(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var r=0;r<q.length;r++){var w=q[r],y=void 0;0<r&&(h=!0);var z=void 0;1===w.nodeType&&(z=w);if(z&&"s"===z.tagName){if((w=(w=z.getAttribute("p"))?this.pens[w]:null)&&w.nf&&(1===w.nf?(w=q.slice(r,r+
4),4===w.length&&(y=F4a(l,m,f,h,n,w,this.pens),r+=3)):y=F4a(l,m,f,h,n,[z],this.pens)),!y){var B=z;y=l;z=m;w=f;var D=h,G=n,C=B.textContent?B.textContent:"",I=B.getAttribute("p");I=I?this.pens[I]:null;B=B5(B,"t")||0;y=new w5(y+B,z-B,G,w,C,D,I)}}else y=new w5(l,m,n,f,w.textContent||"",h,p);c.push(y);this.B=y}if(0<c.length)for(c[0].windowId===this.F&&(this.j=I4a(this,a,b,!0),d.push(this.j)),a=g.t(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var G5a=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(G5,z5);G5.prototype.reset=function(){this.B.clear()};
G5.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.t(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.yH=H5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=H5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=H5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.nf=10<h?h-1:h,f.Vl=G5a.get(f.nf));e.hgHorizGroup&&(f.EQ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.t(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.F.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Rw=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.yh=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.VL=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=H5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.F.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.t(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.gj=e.ahHorPos),void 0!==e.apPoint&&(f.zk=e.apPoint),void 0!==e.avVerPos&&(f.Wl=e.avVerPos),void 0!==e.ccCols&&(f.Sp=e.ccCols),void 0!==e.rcRows&&(f.gp=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.t(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=J4a(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+y5++,h=J4a(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var r=p[l],w=r.utf8;if(w){var y=r.tOffsetMs||0,z=null;r.pPenId&&(z=this.j.get(r.pPenId));if(2===(null!=h.params.Rw?h.params.Rw:1<h.j.length?1:0)&&m&&"\n"===w)continue;if(r=z&&1===z.nf)if(r=l,r+3>=p.length||!p[r+1].pPenId||!p[r+2].pPenId||!p[r+3].pPenId)r=!1;else{var B=p[r+1].pPenId;(B=this.j.get(B))&&B.nf&&2===B.nf?(B=p[r+2].pPenId,B=this.j.get(B),!B||!B.nf||3>B.nf?r=!1:(B=p[r+3].pPenId,r=(B=this.j.get(B))&&
B.nf&&2===B.nf?!0:!1)):r=!1}if(r){y=p[l+1].utf8;r=p[l+3].utf8;B=p[l+2].utf8;var D=this.j.get(p[l+2].pPenId);w=E4a(w,y,B,r,D);m=new w5(d,e,n,f,w,m,z);l+=3}else m=new w5(d+y,e-y,n,h.id,w,m,z||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};L4a.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
L4a.prototype.reset=function(){this.mode=0;this.C.reset(0);this.F.reset(1)};
var M4a=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];I5.prototype.set=function(a){this.type=a};
I5.prototype.get=function(){return this.type};
J5.prototype.clear=function(){this.state=0};
J5.prototype.update=function(){this.state=2===this.state?1:0};
J5.prototype.isValid=function(){return 0!==this.state};
J5.prototype.matches=function(a,b){return this.isValid()&&a===this.rs&&b===this.Op};
R4a.prototype.reset=function(){this.timestamp=this.j=0};
K5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
K5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
K5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var S4a=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],T4a=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],U4a=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],V4a=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Z4a.prototype.reset=function(a,b){this.F=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
K4a.prototype.reset=function(a){this.F=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};c5a.prototype.C=function(){};g.v(P5,c5a);P5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+y5++;c=c/1E3-this.I;d=d/1E3-this.I;a=new x5(c,d-c,5,f,{textAlign:0,zk:0,gj:2.5*b,Wl:5.33*a});e=new w5(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.v(S5,z5);S5.prototype.u=function(a){a=new P5(a,a.byteLength,this.B);if(d5a(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=R5(a)*(1E3/45):1===a.version&&(a.B=4294967296*R5(a)+R5(a)),a.F=Q5(a);0<a.F;a.F--){var b=Q5(a),c=Q5(a),d=Q5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,aP:c,bP:d,order:b.j.length}))}Q4a(this.j,a);return a.u}return[]};
S5.prototype.reset=function(){this.j.clear()};g.v(T5,z5);
T5.prototype.u=function(a,b){var c=[];a=a.split(H5a);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!I5a.test(e)){var h=J5a.exec(e);if(h&&4<=h.length){var l=g5a(h[1]),m=g5a(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,w="";n=g.t(n);for(var y=n.next();!y.done;y=n.next())if(y=y.value.split(":"),2===y.length){var z=y[1];switch(y[0]){case "line":y=z.split(",");y[0].endsWith("%")&&(p=y[0],h.Wl=Number.parseInt(p,10),2===y.length&&(q=y[1].trim()));break;case "position":y=
z.split(",");r=y[0];h.gj=Number.parseInt(r,10);2===y.length&&(w=y[1].trim());break;case "align":switch(z){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.gj=0;break;case 1:h.gj=100;break;case 2:h.gj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(w){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.zk=q}e=e.substring(J5a.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=h5a(l,m,5,w),m=new w5(l,m,5,f.id,h,!1,g.Df(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(K5a),1===q.length?(h=5,w=h5a(l,m,h,w)):(p=h=6,w=Object.assign({Sp:32},w),w=new x5(l,m,p,"_"+y5++,w)),c.push(w),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(y=g.PYa("<html>"+n+"</html>"),y.getElementsByTagName("parsererror").length?
(z=y.createElement("span"),z.appendChild(y.createTextNode(n))):z=y.firstChild,f5a(this,p,m-(p-l),h,w,0<r,z,e,c)):p=g5a(n)+f}J5a.lastIndex=0}}return c};
var I5a=/^NOTE/,H5a=/(?:\r\n|\r|\n){2,}/,J5a=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),K5a=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.QS.ED(T5,{u:"wvppt"});g.v(U5,g.L);U5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
U5.prototype.reset=function(){this.parser&&this.parser.reset()};
U5.prototype.ra=function(){g.L.prototype.ra.call(this);this.clear()};var c6={windowColor:"#080808",windowOpacity:0,textAlign:2,zk:7,gj:50,Wl:100,isDefault:!0,Zd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(V5,g.yO);g.k=V5.prototype;g.k.ra=function(){if(this.C||this.Z){var a=this.G.Wd();a&&!a.isDisposed()&&a.Nv()}else E5a(this,!1);g.yO.prototype.ra.call(this)};
g.k.fu=function(){if(this.Pa)return this.C||this.Z;var a=e4a(this.player.getAudioTrack(),f4a(this.Y));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?W5(this):v5a(this)||W5(this)?!0:w5a(this)};
g.k.load=function(){var a=this;g.yO.prototype.load.call(this);var b=!this.Y.N("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.u?(this.j&&(this.Ua.clear(),this.C?z5a(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Iq(this.j,"json3",function(c,d,e,f){if(c){a.u.RK()&&(a.ya=[],a.G.Bf("captions"),g.eo(a.Aa),a.Ua.reset());c=n5a(a.Ua,c,d,e,f);a.player.me(c,void 0,a.bb);if(!(!a.ea||a.Z||Z5(a)||g.kG(a.Y)||g.bG(a.Y))){g.io(a.Ba);c=D4a({zk:0,gj:5,Wl:5,
gp:2,textAlign:0,yh:0,lang:"zh-CN"});a.Ia=[c];e=["\u70b9\u51fb "," \u67e5\u770b\u8bbe\u7f6e"];a.ib||(f=new g.iL(g.AL()),g.N(a,f),a.ib=f.element);f=c.end-c.start;var h=g.RG(a.j);h&&a.Ia.push(new w5(c.start,f,0,c.id,h));a.Ia.push(new w5(c.start,f,0,c.id,e[0]),new w5(c.start,f,0,c.id,a.ib,!0),new w5(c.start,f,0,c.id,e[1],!0));a.player.me(a.Ia);g.go(a.Ba)}!a.ea||a.Z||Z5(a)||(g.yG(a.Y)?a6(a,!0):b6(a,"module-enabled",!0),a.I&&(a.I.C=a.j),a.player.wu());var l;null==(l=a.G.Kc())||l.va("cc",{kind:d.kind});
a.ea=!1}}),!b||this.C||this.Z||Z5(this)||this.player.Oa("captionschanged",g.SG(this.j))),b||(this.j&&!Z5(this)?this.player.Oa("captionschanged",g.SG(this.j)):this.player.Oa("onCaptionsTrackListChanged"))):(this.u=x5a(this),g.N(this,this.u),this.u.Nw(function(){y5a(a)}))};
g.k.unload=function(){this.C&&this.j?z5a(this,!1):(this.Ba&&g.io(this.Ba),this.player.Bf("captions"),this.ya=[],this.u&&this.u.xp(),this.Ua.clear(),this.J&&this.player.me(this.J),this.sM());g.yO.prototype.unload.call(this);this.player.wu();this.player.Oa("captionschanged",{})};
g.k.create=function(){this.fu()&&this.load()};
g.k.w4=function(){for(var a=this.G.Wd().Df().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.zO(this.u.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.j:null)!==b&&$5(this,b,!0)};
g.k.i7=function(){!this.j&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.ya.push(a);g.eo(this.Aa)};
g.k.onCueRangeExit=function(a){g.cc(this.ya,a);this.u instanceof r5&&this.u.I&&this.player.uh([a]);g.eo(this.Aa)};
g.k.getCaptionWindowContainerId=function(){return this.Xa.element.id};
g.k.q5=function(){D5a(this,this.Ia);this.Ia=null};
g.k.pM=function(){var a=this;if(!this.Cb||!this.C){this.Aa.stop();g.Cca(this.La);this.ya.sort(g.rA);var b=this.ya;if(this.J){var c=g.Em(b,function(f){return-1===this.J.indexOf(f)},this);
c.length&&(b=c)}b=g.t(b);for(c=b.next();!c.done;c=b.next())B5a(this,c.value);b={};c=g.t(Object.entries(this.S));for(var d=c.next();!d.done;b={Lr:b.Lr,rl:b.rl},d=c.next()){var e=g.t(d.value);d=e.next().value;e=e.next().value;b.Lr=d;b.rl=e;this.La[b.Lr]?(b.rl.element.parentNode||(b.rl instanceof v5||b.rl instanceof u5||g.tf(this.S,function(f){return function(h,l){l!==f.Lr&&h.u.params.zk===f.rl.u.params.zk&&h.u.params.gj===f.rl.u.params.gj&&h.u.params.Wl===f.rl.u.params.Wl&&(h.dispose(),delete a.S[l]);
return l===f.Lr}}(b),this),C5a(this,b.rl.element)),b.rl.zx(this.La[b.Lr])):(b.rl.dispose(),delete this.S[b.Lr])}}};
g.k.w5=function(){r5a(this,{},!0);this.Y.N("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Oa("captionssettingschanged")};
g.k.p_=function(){var a=c6.Zd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:c6.windowColor,windowOpacity:c6.windowOpacity};var b=s5a(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.sU=function(a,b){var c={};Object.assign(c,s5a(this));Object.assign(c,a);r5a(this,c,b);this.player.Oa("captionssettingschanged")};
g.k.sM=function(){!this.C&&this.loaded&&(g.qf(this.S,function(a,b){a.dispose();delete this.S[b]},this),this.pM())};
g.k.Gg=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Ng(b,-2,4);this.sU({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&$5(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.Y.F&&(g.yG(this.Y)?a6(this,!!b):b6(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Na(b))break;if(g.Df(b)){$5(this,null,!0);break}a=g.zO(this.u.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?g4a(e,b.translationLanguage):e)}!c||c===this.j&&this.loaded||(b=g.wya(),a=g.TG(c),b.length&&a===b[b.length-1]||(b.push(a),g.Nz("yt-player-caption-language-preferences",b)),$5(this,c,!0))}else return this.loaded&&this.j&&!Z5(this)?g.SG(this.j):{};return"";case "tracklist":return this.u?g.Vk(g.zO(this.u.j,!(!b||!b.includeAsr)),function(f){return g.SG(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||E5a(this,!!b);break;case "sampleSubtitlesCustomized":this.C||E5a(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.F&&a.push("stickyLoading");return a};
g.k.LI=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.Y.N("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.TG(a));return{cc:b}}return{}};
g.k.N6=function(){this.loaded&&this.j&&!Z5(this)?(g.yG(this.Y)?a6(this,!1):b6(this,"module-enabled",!1),this.unload(),W5(this,!0)&&$5(this,X5(this),!1)):this.VT()};
g.k.VT=function(){this.loaded&&this.j&&!Z5(this)||$5(this,Z5(this)||!this.j?Y5(this,!0):this.j,!0)};
g.k.X1=function(){var a=Z5(this);W5(this,a)?$5(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.fu()&&(a?$5(this,Y5(this),!1):this.load()))};
g.k.R2=function(){var a=this.G.Wd();a&&!a.isDisposed()&&a.Nv();this.G.isFullscreen()?(this.C=this.Pa=!0,this.loaded&&y5a(this)):(this.Pa="3"===this.Y.controlsType,this.C=q5a(this));$5(this,this.j)};
g.QS.ED(V5,{pM:"smucd"});g.xO("captions",V5);})(_yt_player);
