(function(g){var window=this;'use strict';var s4a=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},t4a=function(a){return g.FG(a)&&!a.N("web_player_i_see_captions_3_killswitch")},u4a=function(a){return g.FG(a)?g.mF(a.experiments,"web_player_caption_language_preference_stickiness_duration"):0},v4a=function(a,b){var c=new g.aH;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},w4a=function(a,b){var c,d,e;
return g.A(function(f){if(1==f.j)return c=a+"|"+b,g.x(f,g.Pw(),2);if(3!=f.j){d=f.u;if(!d)throw g.pw("gct");return g.x(f,g.MH(d),3)}e=f.u;return f.return(e.get("captions",c))})},x4a=function(a,b,c){w4a(a,b).then(function(d){d&&c(d.trackData,new g.aH(d.metadata))})},A4a=function(a){if(!y4a.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(z4a,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},r5=function(){this.segments=[]},B4a=function(a,b){var c=g.rc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.ec(a.segments,c),g.ec(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.pc(a.segments,c,0,b),g.pc(a.segments,c+1,0,b)))},C4a=function(a,b,c,d,e,f){g.M.call(this);
this.policy=a;this.player=b;this.ea=c;this.S=d;this.F=e;this.Z=f;this.Y=this.player.V();this.C=new r5;this.I=-1;this.B=this.u=this.j=null;this.J=new g.io(this.iR,1E3,this);this.events=new g.nE(this);g.N(this,this.J);g.N(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.Rw);this.Rw();this.iR()},D4a=function(a){return a.j&&a.j.B?a.j.B+a.player.Ad()<a.player.getCurrentTime():!1},E4a=function(a,b){var c=g.GD(b,a.policy,{}).Be(),d={format:"RAW",
withCredentials:!0};a.policy.Pa&&(d.method="POST",d.postBody=b.Rs()||(0,g.MV)([120,0]));a.F&&(d.responseType="arraybuffer");a.B=g.Wu(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.F?e.response:e.responseText)||400<=e.status,h=g.Lxa(e);if(h){e=g.GD(a.u,a.policy,{});a.u.Ek(e,h);E4a(a,a.u);break a}f?a.player.va("capfail",{status:e.status}):(a.player.Ti().Fi("fcb_r"),h=a.u.j[0].Na,null!=a.S&&a.I!==h&&(f=a.u.j[0],a.F?a.S(e.response,1E3*(f.startTime+a.player.Ad())):a.S(e.responseText,
1E3*(f.startTime+a.player.Ad())),a.I=h))}a.u=null;a.B=null}}).mj(function(e){a.u=null;
a.B=null;var f;a.player.va("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;B4a(a.C,a.u.j[0].Na)},s5=function(a,b){g.OO.call(this,b.V());
this.u=a;this.G=b;this.B=null;this.F=!1;this.I=g.HG(this.G.V())&&!this.u.isManifestless},G4a=function(a,b){var c=[],d;
for(d in a.u.j)if(a.u.j.hasOwnProperty(d)){var e=a.u.j[d];if(g.RO(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.t2a.get(e);null==n&&(n=F4a[e]||F4a[e.replace(/-/g,"_")],g.t2a.set(e,n));h=n||h}c.push(new g.aH({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},H4a=function(a,b){return null!=b&&b in a.u.j?a.u.j[b]:null},I4a=function(a,b,c){var d=
[],e;
for(e in a.u.j)if(a.u.j.hasOwnProperty(e)){var f=a.u.j[e];if(g.RO(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},t5=function(a,b,c,d,e,f,h,l){var m={};
Object.assign(m,b);Object.assign(m,a.params);Object.assign(m,c);var n={};Object.assign(n,b.Yd);a.params.Yd&&Object.assign(n,a.params.Yd);Object.assign(n,c.Yd);m.Yd=n;g.X.call(this,{D:"div",K:"caption-window",X:{id:"caption-window-"+a.id,dir:1===m.uh?"rtl":"ltr",tabindex:"0",lang:m.lang},W:[{D:"span",K:"captions-text",X:{style:"word-wrap: normal; display: block;"}}]});this.F=[];this.Ba=!1;this.u=a;this.La=this.Ia=null;this.playerWidth=f;this.playerHeight=h;this.I=null;this.maxWidth=.96*f;this.Xa=.96*
h;this.j=m;this.Nb=c;this.ea=b;this.C=this.Ca("captions-text");this.Cb=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.oa=e/360*16;!l.gb("web_player_scale_font_size_for_shorts_killswitch")&&e>=d&&(this.oa=f/640*16);this.type=0;this.bb=this.oa*J4a(n);a=new g.pz(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.wV,this);a.subscribe("dragmove",this.vV,this);a.subscribe("dragend",this.uV,this);this.kb=this.ib=
0;b="";this.j.windowOpacity&&(a=A4a(this.j.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");a={"background-color":b,display:!1===this.j.isVisible?"none":"","text-align":K4a[this.j.textAlign]};this.Cb&&(a["border-radius"]=b?this.bb/8+"px":"");if(this.B=2===this.u.params.uh||3===this.u.params.uh)b=this.element,c="vertical-rl",1===this.j.WL&&(c="vertical-lr"),g.Ic&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Hl(b,"-o-writing-mode",c),g.Hl(b,"-webkit-writing-mode",c),g.Hl(b,"writing-mode",
c),g.Hl(b,"text-orientation","upright"),g.qo(b,"ytp-vertical-caption"),3===this.u.params.uh&&(g.Hl(b,"text-orientation",""),g.Hl(b,"transform","rotate(180deg)"));g.Hl(this.element,a);switch(this.j.vk){case 0:case 1:case 2:g.qo(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.qo(this.element,"ytp-caption-window-bottom")}},J4a=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},L4a=function(a,b){var c={},d=b.background?b.background:a.j.Yd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Yd.backgroundOpacity;d=A4a(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Cb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.bb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.oa*J4a(b)+"px";d=1;e=b.color||a.j.Yd.color;if(b.color||null!=b.textOpacity)e=A4a(e),d=null==b.textOpacity?a.j.Yd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.zH&&(h=e=b.zH);var l=a.oa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.gv()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Yd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.T_&&(c.visibility="hidden");1===b.EQ&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.LG||g.nw,3===a.u.params.uh?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Sl||2===b.Sl||3===b.Sl||4===b.Sl||5===b.Sl)if(g.LG)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Sl){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},M4a=function(a){a.I=g.mh("SPAN");
g.Hl(a.I,{display:"block"});g.qo(a.I,"caption-visual-line");a.C.appendChild(a.I)},N4a=function(a,b){var c=g.mh("SPAN");
g.Hl(c,{display:"inline-block","white-space":"pre-wrap"});g.Hl(c,L4a(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.Hl(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Hl(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},O4a=function(a,b,c){a.Ba=a.Ba||!!c;
var d={};Object.assign(d,a.j.Yd);Object.assign(d,c||b.j);Object.assign(d,a.Nb.Yd);(c=!a.I)&&M4a(a);for(var e=a.Ia&&a.La&&g.Hf(d,a.La)?a.Ia:N4a(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(M4a(a),e=N4a(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.nh(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.LG||!g.Jl(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Jl(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.jf?g.Hl(e,m,"1em"):g.Hl(e,m,"0.5em")))}a.La=d;a.Ia=e;a.F.push(b)},u5=function(a,b,c,d){g.OO.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ua=d;this.C=b.xH},v5=function(a,b,c,d,e,f,h,l){t5.call(this,a,b,c,d,e,f,h,l);
this.type=1},w5=function(a,b,c,d,e,f,h,l){t5.call(this,a,b,c,d,e,f,h,l);
this.type=2;this.J=[];this.Z=this.S=this.Pa=0;this.Aa=NaN;this.sb=0;this.Ob=null;this.Sa=new g.io(this.M3,433,this);g.qo(this.element,"ytp-caption-window-rollup");g.N(this,this.Sa);g.Hl(this.element,"overflow","hidden")},P4a=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.WL&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},Q4a=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.bp,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.S=d;b=Math;c=b.max;isNaN(a.Aa)&&((d=a.j.Op)?(e=g.mh("SPAN"),g.th(e,"\u2013".repeat(d)),g.Hl(e,L4a(a,a.j.Yd)),a.C.appendChild(e),a.Aa=e.offsetWidth,a.C.removeChild(e)):a.Aa=0);d=a.C;a.Z=c.call(b,a.Aa,a.sb,(a.B?d.offsetHeight:d.offsetWidth)+1)},R4a=function(a,b){Q4a(a);
var c=a.J.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.S-c;if(c!==a.Pa){var d=0<c&&0===a.Pa;b||isNaN(c)||d||(g.qo(a.element,"ytp-rollup-mode"),g.jo(a.Sa));g.Hl(a.C,"transform",P4a(a,c));a.Pa=c}Q4a(a)},x5=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.AA.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},y5=function(a,b,c,d,e){g.AA.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},S4a=function(a){var b="_"+z5++;
return new y5(0,0x8000000000000,0,b,a)},U4a=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.mf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=T4a(l.textContent,n.textContent,p.textContent,f.textContent,h);return new x5(a,b,e,c,l,d,m)}switch(m.mf){case 9:case 10:m.Sl=1;break;case 11:m.Sl=2;break;case 12:m.Sl=3;break;case 13:m.Sl=4;break;case 14:m.Sl=5}return new x5(a,b,e,c,l.textContent||"",d,m)},T4a=function(a,b,c,d,e){var f=g.gv(),h=
f?g.mh("DIV"):g.mh("RUBY"),l=g.mh("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.mh("DIV"):g.mh("RP");a.textContent=b;h.appendChild(a);b=f?g.mh("DIV"):g.mh("RT");b.textContent=c;h.appendChild(b);c=e.mf;if(10===c||11===c||12===c||13===c||14===c)if(g.Hl(b,"text-emphasis-style","filled circle"),g.Hl(b,"text-emphasis-color","currentcolor"),g.Hl(b,"webkit-text-emphasis","filled circle"),11===e.mf||13===e.mf)g.Hl(b,"webkit-text-emphasis-position","under left"),g.Hl(b,"text-emphasis-position","under left");c=!0;if(4===e.mf||7===e.mf||12===e.mf||
14===e.mf)g.Hl(h,"ruby-position","over"),g.Hl(h,"-webkit-ruby-position","before");else if(5===e.mf||6===e.mf||11===e.mf||13===e.mf)g.Hl(h,"ruby-position","under"),g.Hl(h,"-webkit-ruby-position","after"),c=!1;e=f?g.mh("DIV"):g.mh("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Hl(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Hl(f,"display","none"),f=f.nextElementSibling,g.Hl(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Hl(h.lastElementChild,"display","none"),d?(g.Hl(h,"padding-top","0.6em"),g.Hl(f,"top","0")):(g.Hl(h,"padding-bottom","0.6em"),g.Hl(f,"bottom","0")));return h},A5=function(){g.M.apply(this,arguments)},B5=function(a){A5.call(this);
this.C=a;this.pens={};this.S={};this.Z={};this.F="_"+z5++;this.J={};this.B=this.j=null;this.I=!0},C5=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},D5=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},E5=function(a,b){a=C5(a,b);
return void 0!==a?a:null},G5=function(a,b){a=a.getAttribute(b);
if(null!=a)return F5.test(a),a},V4a=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=E5(b,"mh");null!=a&&(c.Ow=a);a=E5(b,"ju");null!=a&&(c.textAlign=a);a=E5(b,"pd");null!=a&&(c.uh=a);a=E5(b,"sd");null!=a&&(c.WL=a);a=G5(b,"wfc");null!=a&&(c.windowColor=a);b=C5(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},W4a=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.S[d]);a=E5(b,"ap");null!=a&&(c.vk=a);a=C5(b,"cc");null!=a&&(c.Op=a);a=C5(b,"ah");null!=a&&(c.cj=a);a=C5(b,"rc");null!=a&&(c.bp=a);b=C5(b,"av");null!=b&&(c.Tl=b);return c},X4a=function(a,b,c,d){var e={};
Object.assign(e,W4a(a,b));Object.assign(e,V4a(a,b));d?g.Hf(e,a.C)?(d=a.F,e=a.C):d="_"+z5++:d=b.getAttribute("id")||"_"+z5++;a=C5(b,"t")+c;b=C5(b,"d")||0x8000000000000;if(2===e.uh||3===e.uh)c=e.bp,e.bp=e.Op,e.Op=c;return new y5(a,b,0,d,e)},H5=function(a){A5.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.F=new Map;this.B=new Map},I5=function(a){a=g.Jg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Y4a=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.F.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.bp=a);b=b.ccColCount;void 0!==b&&(f.Op=b);if(2===f.uh||3===f.uh)b=f.bp,f.bp=f.Op,f.Op=b;return new y5(c,d,0,e,f)},$4a=function(){this.B=this.time=this.mode=this.u=0;
this.C=new Z4a(this);this.F=new Z4a(this);this.j=[];this.clear()},b5a=function(a,b,c){if(255===a&&255===b||!a&&!b)return{gs:a,
Kp:b,result:0};a=a5a[a];b=a5a[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Kp===d;if(d)return{gs:a,Kp:b,result:1}}else if(b&128&&1<=a&&31>=a)return{gs:a,Kp:b,result:2};return{gs:a,Kp:b,result:3}},d5a=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.F.u.clear()):(a.B=0,c5a(a.C,b,c,d))},e5a=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.t(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?d5a(a,d.bP,d.cP,b):1===d.type&&a.u&496&&c5a(a.F,d.bP,d.cP,b);a.j.length=0},J5=function(){this.type=0},K5=function(){this.state=this.Kp=this.gs=0},f5a=function(){this.timestamp=this.j=0},L5=function(a){this.F=a;
this.B=[];this.j=this.u=this.row=0;this.style=new J5;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new f5a}},M5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.F.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.F.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},k5a=function(a,b){switch(a){case 0:return g5a[(b&127)-32];
case 1:return h5a[b&15];case 2:return i5a[b&31];case 3:return j5a[b&31]}return 0},N5=function(a){return a.B[a.row][a.u]},O5=function(a,b,c){2<=b&&1<a.u&&(--a.u,N5(a).j=0);
var d=N5(a);d.timestamp=a.F.time+0;d.j=k5a(b,c);32>a.u&&a.u++},l5a=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},P5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},m5a=function(a){a.row=0<a.j?a.j:1;
a.u=1;P5(a,0,15)},n5a=function(a){this.B=a;
this.F=0;this.style=new J5;this.I=new L5(this.B);this.J=new L5(this.B);this.text=new L5(this.B);this.u=this.I;this.C=this.J;this.j=this.u},o5a=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(M5(d,c),m5a(a.u),m5a(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(M5(d,c),P5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},p5a=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},q5a=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},Z4a=function(a){this.j=a;
this.F=0;this.B=new n5a(this.j);this.I=new n5a(this.j);this.u=new K5;this.C=this.B},c5a=function(a,b,c,d){a.u.update();
b=b5a(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.gs;c=b.Kp;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&O5(a,0,b),c&96&&O5(a,0,c),0!==b&&0!==c&&3===a.style.type&&M5(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.gs=e,b.Kp=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.F<<2)+(b.F<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.F<<2)+(b.F<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;l5a(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));P5(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:O5(b.j,0,32);break a;case 48:57===c?(d=b.j,N5(d).j=0,32>d.u&&d.u++):O5(b.j,1,c&15)}break;case 2:c&32&&O5(b.j,2,c&31);break;case 3:c&32&&O5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:p5a(b);
break;case 33:d=b.j;1<d.u&&(--d.u,N5(d).j=0);break;case 36:d=b.j;b=N5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:o5a(b,2,d);break;case 38:o5a(b,3,d);break;case 39:o5a(b,4,d);break;case 40:O5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);m5a(d);q5a(b);break;case 43:q5a(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:M5(a,d)}P5(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;M5(a,d);l5a(a,b,b+1,a.j-1);P5(a,a.row,1)}break;case 46:P5(b.C,0,15);break;case 47:M5(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,p5a(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},r5a=function(){},Q5=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.F=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},R5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},S5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},T5=function(a,b){A5.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new $4a;this.j.u=1<<this.track},t5a=function(a){if("string"===typeof a)return!1;
a=new Q5(a,8,0);return s5a(a)},s5a=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==S5(a))return!1;
a.version=R5(a);if(1<a.version)return!1;R5(a);R5(a);R5(a);return!0},U5=function(){A5.call(this)},u5a=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new x5(b,c,d,e.id,p.nodeValue,f||0<n,g.Ef(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);u5a(a,b,c,d,e,!0,p,q,m)}}},v5a=function(a){var b=a.split(":");
a=0;b=g.t(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},w5a=function(a,b,c,d){d=Object.assign({Ow:0},d);
return new y5(a,b,c,"_"+z5++,d)},V5=function(a,b){g.M.call(this);
this.G=a;this.Y=b;this.parser=null;this.j=this.G.ow()},C5a=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=x5a(a,b,d),l=[];try{for(var m=g.t(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,r=p.ML;l="string"!==typeof q?l.concat(y5a(a,c,q,r,f)):"WEBVTT"===q.substring(0,6)?l.concat(z5a(a,q,r)):l.concat(A5a(a,c,q,r))}var w=l}catch(y){g.zz(y),a.clear(),w=[]}if(0!==w.length)return w}b=B5a(b);if(!b)return[];try{return"string"!==typeof b?y5a(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?z5a(a,b,d):A5a(a,c,b,d)}catch(y){return g.zz(y),a.clear(),[]}},B5a=function(a){if("string"===
typeof a||t5a(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.GC(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.oC(a)},x5a=function(a,b,c){if("string"===typeof b||t5a(b))return[{trackData:b,
ML:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.zwa(d);if(a.j&&e){var f=g.rwa(e),h=g.swa(e);e=e.j;f&&e&&a.j.tB(e,f,h)}f=g.PC(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.t(f.entries());for(h=f.next();!h.done;h=f.next())e=g.t(h.value),h=e.next().value,e=e.next().value,e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.oC(e),a.push({trackData:e,ML:c+1E3*h});D5a(d,a,c);return a=a.filter(function(l){return!!l.trackData})},
D5a=function(a,b,c){var d=g.GC(a,0,1836476516),e=9E4;
d&&(e=g.HC(d)||9E4);d=0;var f=g.PC(a,1836019558);f=g.t(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.t(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.GC(a,l.dataOffset,1953653094))&&(l=g.GC(a,l.dataOffset,1952867444))&&(l=g.NC(l)/e*1E3,0===h&&(d=l),b[h].ML=l-d+c||c*h*1E3)}},y5a=function(a,b,c,d,e){if(!t5a(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new T5(e,b));return a.parser.u(c,d)},z5a=function(a,b,c){a.parser||(a.parser=new U5);
a=a.parser.u(b,c);.01>Math.random()&&g.Az(Error("Deprecated subtitles format in web player: WebVTT"));return a},A5a=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new H5(E5a(b))),a.parser.u(c,d)}catch(f){return g.zz(f),[]}var e=g.$Ya(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new B5(E5a(b),a.Y)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},E5a=function(a){var b=
{};
if(a=g.dH(a))b.lang=a,g.r_a.test(a)&&(b.uh=1);return b},W5=function(a){g.LO.call(this,a);
var b=this;this.G=a;this.Y=this.G.V();this.videoData=this.G.getVideoData();this.sb=this.G.fb();this.B={Yd:{}};this.F={Yd:{}};this.Ba=[];this.Z={};this.Sa={};this.ya=!1;this.hc=g.QI(this.videoData);this.ib=g.EHa(this.videoData,this.G);this.Nb=!!this.videoData.captionTracks.length;this.vc=!!this.videoData.Id;this.Xa="3"===this.Y.controlsType;this.u=this.I=this.J=this.Pa=this.kb=null;this.bb=new V5(this.G,this.Y);this.j=null;this.Aa=new g.nE(this);this.ea=new g.X({D:"div",K:"ytp-caption-window-container",
X:{id:"ytp-caption-window-container"}});this.S={top:0,right:0,bottom:0,left:0,width:1,height:1};var c=null,d=g.Zo("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.No(d));this.storage=c;var e;this.Cb=!(null==(e=a.Vd())||!e.kB());this.C=F5a(this);this.oa=!this.C&&this.Xa&&this.Cb&&this.ib;g.N(this,this.bb);this.C?this.La=this.Ia=null:(this.Ia=new g.go(this.qM,void 0,this),g.N(this,this.Ia),this.La=new g.io(this.q5,2E3,this),g.N(this,this.La));g.N(this,this.Aa);this.Y.N("caption_window_container_killswitch")||
g.fO(this.player,this.ea.element,4);g.N(this,this.ea);this.C||this.Aa.T(a,"resize",this.tM);(this.Ob=(this.Y.N("web_player_track_tag_only_on_fullscreen_for_mweb_killswitch")||g.jG(this.Y))&&!g.ez()&&!this.G.isFullscreen()&&!this.C&&!this.oa)&&this.Aa.T(a,"resize",this.R2);this.Aa.T(a,"onPlaybackAudioChange",this.X1);this.Aa.T(a,g.CA("captions"),function(f){b.onCueRangeEnter(f)});
this.Aa.T(a,g.DA("captions"),function(f){b.onCueRangeExit(f)});
G5a(this,H5a(this)||{})},L5a=function(a){if(1===a.Y.ib||1===a.videoData.aJ||"alwayson"===g.AI(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().B;if(2===a.Y.ib){var c;g.JG(a.Y)?c=I5a(a):c=J5a(a,"module-enabled");if(null!=c)return!!c}c=s4a(a.player.getAudioTrack(),t4a(a.Y));var d=g.AI(a.videoData,"yt:cc");if(void 0===K5a(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===g.AI(a.videoData,"yt:cc")},X5=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.u||"FORCED_ON"===a.B},K5a=function(a){var b=void 0,c=g.Kv(g.Jv.getInstance(),65);
if(g.JG(a.Y)&&null!=c){if(null!=I5a(a))return!1;b=!c}return b},M5a=function(a){var b;
a.hc?b=new u5(a.Y,a.videoData,a.player.getAudioTrack(),a.player):a.ib?b=new s5(a.videoData.j,a.player):a.Nb?b=new g.PO(a.Y,a.videoData,a.player.getAudioTrack()):b=new g.SO(a.Y,a.videoData.Id,a.videoData.videoId,g.$Ba(a.videoData),a.videoData.lm);return b},Z5=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.vc?!1:a.Nb?!1:!0);a.Y.N("web_player_should_honor_include_asr_setting")&&g.FG(a.Y)&&(b=b||!!g.Kv(g.Jv.getInstance(),66));b=g.MO(a.u.j,b);if(u4a(a.Y)){var c=a.G.isInline()?void 0:g.Yz("yt-player-caption-sticky-language");c=[c,a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.AI(a.videoData,"yt:cc_default_lang")];for(var d=!1,e=0;e<c.length;e++){var f=c[e];if(f){d=!0;for(var h=0;h<b.length;h++)if(g.dH(b[h])===f)return b[h];f=f.split("-")[0];for(h=0;h<b.length;h++)if(g.dH(b[h])===
f)return b[h]}}if(d){var l;return(null==(l=a.I)?void 0:l.j)||Y5(a)}}else for(l=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.AI(a.videoData,"yt:cc_default_lang")],c=0;c<l.length;c++)for(d=0;d<b.length;d++)if(g.dH(b[d])===l[c])return b[d];return a.I&&a.I.j?a.I.j:(l=b.find(function(m){return m.isDefault}))?l:b[0]||Y5(a)}return null},Y5=function(a){return a.I&&a.I.u},$5=function(a){var b=Y5(a);
return!!b&&a.j===b},N5a=function(a){g.MO(a.u.j,!0);
var b=s4a(a.player.getAudioTrack(),t4a(a.Y)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=Z5(a,a.ya):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&X5(a)?c=Y5(a):K5a(a)||a.ya||L5a(a)?c=Z5(a,a.ya):X5(a)&&(c=Y5(a));if(a.C||a.oa){var d=g.MO(a.u.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.mh("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.bH(f));h.setAttribute("srclang",g.dH(f));h.setAttribute("id",f.toString());a.oa||h.setAttribute("src",a.u.Qs(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.G.Vd();c.Ky(b);c=c.Cf();a.Cb&&a.Aa.T(c.textTracks,"change",a.v4)}else!a.j&&c&&a6(a,c),a.player.Oa("onCaptionsTrackListChanged"),a.player.Oa("onApiChange")},O5a=function(a,b){var c=a.G.Vd().Cf().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},a6=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ya=c,a.ya&&(g.JG(a.Y)?b6(a,!!b):c6(a,"module-enabled",!!b)));a.j=b;X5(a)&&(a.j=Y5(a));a.load()},Q5a=function(a,b){if(b instanceof y5){var c=a.Z[b.id];
c&&c.u!==b&&(c.dispose(),delete a.Z[b.id],c=null);c||(c=P5a(a,b))&&(a.Z[b.id]=c)}else c=b.windowId,a.Sa[c]||(a.Sa[c]=[]),a.Sa[c].push(b)},R5a=function(a,b){a.Y.N("caption_window_container_killswitch")?g.fO(a.player,b,4):a.ea.element.appendChild(b)},P5a=function(a,b){var c=a.sb.getVideoContentRect(!0).height,d=a.sb.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.dH(a.j):null;e&&g.r_a.test(e)&&(b.params.uh=1);var f=a.sb.getPlayerSize();c*=a.S.height;d*=a.S.width;e=f.height*a.S.height;f=f.width*a.S.width;a.Y.N("web_player_caption_stickiness_for_glive_killswitch")||"google-live"!==a.Y.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.Ow?b.params.Ow:1<b.j.length?1:0){case 1:return new v5(b,a.B,a.F,d,c,f,e,a.Y.experiments);case 2:return new w5(b,a.B,a.F,d,c,f,e,a.Y.experiments);default:return new t5(b,
a.B,a.F,d,c,f,e,a.Y.experiments)}},G5a=function(a,b,c){c=void 0===c?!1:c;
var d=d6.Yd;a.B={};Object.assign(a.B,d6);a.B.Yd={};Object.assign(a.B.Yd,d);a.F={Yd:{}};var e=b.backgroundOverride?a.F:a.B,f=b.background||d.background;F5.test(f);e.Yd.background=f;e=b.colorOverride?a.F:a.B;f=b.color||d.color;F5.test(f);e.Yd.color=f;e=b.windowColorOverride?a.F:a.B;f=b.windowColor||d6.windowColor;F5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Yd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Yd.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Yd;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.F:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Yd.textOpacity=f;e=b.windowOpacityOverride?a.F:a.B;f=b.windowOpacity;null==f&&(f=d6.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.F:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Yd.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Yd.fontFamily=f;a.loaded&&a.tM();c&&(a.Y.N("web_player_local_storage_for_captions_setting_killswitch")?c6(a,"display-settings",b):g.Xz("yt-player-caption-display-settings",b,2592E3))},T5a=function(a,b,c){b&&!a.J?(b=S4a({uh:0,
lang:"zh-CN"}),a.J=[b,new x5(b.start,b.end-b.start,0,b.id,null!=c?c:"\u5b57\u5e55\u6837\u5f0f\u9884\u89c8")],a.player.le(a.J)):!b&&a.J&&(S5a(a,a.J),a.J=null)},S5a=function(a,b){a.player.qh(b);
b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.fc(a.Ba,c.value);g.ho(a.Ia)},U5a=function(a,b){b&&(a.S={top:b.top,
right:b.right,bottom:b.bottom,left:b.left,width:1-b.left-b.right,height:1-b.top-b.bottom},a.ea.element.style.top=100*a.S.top+"%",a.ea.element.style.left=100*a.S.left+"%",a.ea.element.style.width=100*a.S.width+"%",a.ea.element.style.height=100*a.S.height+"%")},J5a=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},c6=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},b6=function(a,b){a.G.isInline()||g.Xz("yt-player-sticky-caption",b,2592E3)},I5a=function(a){if(!a.G.isInline())return g.Yz("yt-player-sticky-caption")},H5a=function(a){return a.Y.N("web_player_local_storage_for_captions_setting_killswitch")?J5a(a,"display-settings"):g.Yz("yt-player-caption-display-settings")},F5a=function(a){var b,c=!(null==(b=a.G.Vd())||!b.jB());
return a.Xa&&c&&!a.ib};
g.qT.prototype.sz=g.ca(39,function(a){var b=2;this.La.has(a)?b=0:g.$Ka(this,a)&&(b=1);return b});
g.lW.prototype.sz=g.ca(38,function(a){return this.qd.sz(a)});
g.qT.prototype.tB=g.ca(37,function(a,b,c){this.Ba.set(a,{Es:b,Hy:c})});
g.lW.prototype.tB=g.ca(36,function(a,b,c){this.qd.tB(a,b,c)});
g.fP.prototype.Kv=g.ca(31,function(){for(var a=g.dh(document,"track",void 0,this.j),b=0;b<a.length;b++)g.qh(a[b])});
g.aT.prototype.Kv=g.ca(30,function(){this.mediaElement.Kv()});
g.fP.prototype.kB=g.ca(29,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.aT.prototype.kB=g.ca(28,function(){return this.mediaElement.kB()});
g.fP.prototype.jB=g.ca(27,function(){return!!this.j.textTracks});
g.aT.prototype.jB=g.ca(26,function(){return this.mediaElement.jB()});
g.fP.prototype.Ky=g.ca(25,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.aT.prototype.Ky=g.ca(24,function(a){this.mediaElement.Ky(a)});
g.OO.prototype.SK=g.ca(23,function(){return!1});
g.OO.prototype.Fq=g.ca(22,function(){});
g.PO.prototype.Fq=g.ca(21,function(a,b,c){var d=this;this.isDisposed();b=this.Qs(a,b);this.rp();this.u=g.Tu(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.SO.prototype.Fq=g.ca(20,function(a,b,c){var d=this;this.isDisposed();b=this.Qs(a,b);this.rp();this.u=g.Tu(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.ZV.prototype.Hz=g.ca(10,function(){return this.J});
g.FY.prototype.Hz=g.ca(9,function(){var a;return(null==(a=g.UN(this))?void 0:a.ow())||null});
g.ZN.prototype.ow=g.ca(8,function(){return this.app.Hz()});
g.fY.prototype.ow=g.ca(7,function(){var a;return(null==(a=this.Ja)?void 0:a.Hz())||null});
g.bC.prototype.pD=g.ca(3,function(a){return(a=this.Om(a))?a.j:0});
g.UD.prototype.pD=g.ca(2,function(){return 0});
var z4a=/#(.)(.)(.)/,y4a=/^#(?:[0-9a-f]{3}){1,2}$/i,F4a={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgn:"Western Balochi",bho:"Bhojpuri",
bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",
chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",
goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",
ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",
kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",
lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",
mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",
ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};r5.prototype.contains=function(a){a=g.rc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
r5.prototype.length=function(){return this.segments.length/2};
g.v(C4a,g.M);g.k=C4a.prototype;g.k.ra=function(){g.M.prototype.ra.call(this);this.B&&this.B.cancel()};
g.k.Rw=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Ad();var b=this.j;this.j=g.Vb(this.ea.Sm(a).j);b!==this.j&&this.Z&&this.Z()};
g.k.reset=function(){this.C=new r5;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.iR=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Bp(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.zy(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)if(b=this.player.ow()){var c=a.j[0].j.info.id,d=a.j[0].Na,e=a.j[0].C;if(this.policy.Pa){if(b=b.Rs(e,d,c,3))a.S=b}else if(c=b.Pm(e,d,c,3))if(b=b.sz(d),0===b)c&&(a.B=new g.VB(c));else if(2===b){this.J.start();D4a(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.j[0].duration?(this.C.contains(a.j[0].Na)||E4a(this,a),this.j=g.Vb(a.j)):!this.Y.N("force_caption_seek_for_live_killswitch")&&D4a(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.v(s5,g.OO);g.k=s5.prototype;g.k.Fq=function(a,b,c){var d=this;this.rp();b=H4a(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?I4a(this,b,"386"):I4a(this,b));if(b){var e=1E3*(b.index.pD(b.index.Bl())-b.index.getStartTime(b.index.Bl())),f=new g.QO(this.Y);this.B=new C4a(f,this.G,b,function(h,l){c(h,a,l,e)},this.I||g.SD(b.info),function(){d.B&&d.B.reset();
d.F=!0})}};
g.k.SK=function(){var a=this.F;this.F=!1;return a};
g.k.Kw=function(a){var b=this.I?[new g.aH({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.aH({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?G4a(this,"386"):G4a(this);b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.NO(this.j,c.value);a()};
g.k.rp=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Qs=function(){return""};
var F5=/^#(?:[0-9a-f]{3}){1,2}$/i;var K4a=["left","right","center","justify"];g.v(t5,g.X);g.k=t5.prototype;g.k.wV=function(a,b){var c=g.Ql(this.element,this.element.parentElement);this.ib=a-c.x;this.kb=b-c.y;g.qo(this.element,"ytp-dragging")};
g.k.vV=function(a,b){var c=g.Sl(this.element);a=a-this.ib-.02*this.playerWidth;var d=b-this.kb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Jg(e,0,2));var f=(d+c.height/2)/this.Xa*3;f=Math.floor(g.Jg(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Jg(a,0,1);c=(d+f/2*c.height)/this.Xa;c=100*g.Jg(c,0,1);this.u.params.vk=b;this.u.params.Tl=c;this.u.params.cj=a;this.u.params.isDefault=!1;this.j.vk=b;this.j.Tl=c;this.j.cj=a;this.j.isDefault=!1;this.ea.vk=b;this.ea.Tl=c;
this.ea.cj=a;this.ea.isDefault=!1;this.gT()};
g.k.uV=function(){g.so(this.element,"ytp-dragging")};
g.k.gT=function(){this.wx(this.F)};
g.k.getType=function(){return this.type};
g.k.wx=function(a){var b=Math.min(this.XP(),this.maxWidth),c=this.WP(),d="";3===this.u.params.uh&&(d="rotate(180deg)");g.Hl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.jH(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.cj+2;d=this.j.vk;switch(d){case 0:case 3:case 6:(b=this.j.Yd.fontSizeIncrement)&&0<b&&2!==this.j.uh&&3!==
this.j.uh&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.j.Tl+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Hl(this.element,
a)};
g.k.jH=function(a){var b;for(b=0;b<a.length&&a[b]===this.F[b];b++);if(this.Ba||this.F.length>b)b=0,this.Ba=!1,this.F=[],this.I=this.La=this.Ia=null,g.oh(this.C);for(;b<a.length;b++)O4a(this,a[b])};
g.k.XP=function(){return 0};
g.k.WP=function(){return 0};
g.k.toString=function(){return g.X.prototype.toString.call(this)};g.v(u5,g.OO);u5.prototype.Fq=function(a,b,c){x4a(this.videoData.videoId,a.vssId,c)};
u5.prototype.Kw=function(a){if(this.audioTrack)for(var b=g.t(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.NO(this.j,c.value);a()};g.v(v5,t5);v5.prototype.jH=function(a){var b=this.u.j;t5.prototype.jH.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,V5a);var e=c.j;var f=d}O4a(this,c,d)}};
var V5a={T_:!0};g.v(w5,t5);g.k=w5.prototype;g.k.gT=function(){g.ko(this.Sa)};
g.k.M3=function(){g.so(this.element,"ytp-rollup-mode");this.wx(this.Ob,!0)};
g.k.WP=function(){return this.B?this.Z:this.S};
g.k.XP=function(){return this.B?this.S:this.Z};
g.k.wx=function(a,b){this.Ob=a;if(this.u.params.bp){for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));this.sb=this.Z;this.S=this.Z=0;t5.prototype.wx.call(this,a);R4a(this,b)}t5.prototype.wx.call(this,a)};g.v(x5,g.AA);x5.prototype.toString=function(){return g.AA.prototype.toString.call(this)};g.v(y5,g.AA);y5.prototype.toString=function(){return g.AA.prototype.toString.call(this)};
var z5=0;g.v(A5,g.M);A5.prototype.u=function(){return[]};
A5.prototype.reset=function(){};g.v(B5,A5);B5.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
B5.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.t(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.t(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=D5(a,"b");
null!=l&&(h.bold=l);l=D5(a,"i");null!=l&&(h.italic=l);l=D5(a,"u");null!=l&&(h.underline=l);l=E5(a,"et");null!=l&&(h.charEdgeStyle=l);l=E5(a,"of");null!=l&&(h.offset=l);l=G5(a,"bc");null!=l&&(h.background=l);l=G5(a,"ec");null!=l&&(h.zH=l);l=G5(a,"fc");null!=l&&(h.color=l);l=E5(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=C5(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=C5(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=C5(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=E5(a,"rb");null!=l&&10!==l&&
0!==l&&(h.mf=10<l?l-1:l);a=E5(a,"hg");null!=a&&(h.EQ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=V4a(this,a);break;case "wp":c=a.getAttribute("id"),this.S[c]=W4a(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.t(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=X4a(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.F;
h=!!D5(a,"a");l=(C5(a,"t")||0)+l;var m=C5(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var r=0;r<q.length;r++){var w=q[r],y=void 0;0<r&&(h=!0);var z=void 0;1===w.nodeType&&(z=w);if(z&&"s"===z.tagName){if((w=(w=z.getAttribute("p"))?this.pens[w]:null)&&w.mf&&(1===w.mf?(w=q.slice(r,r+
4),4===w.length&&(y=U4a(l,m,f,h,n,w,this.pens),r+=3)):y=U4a(l,m,f,h,n,[z],this.pens)),!y){var B=z;y=l;z=m;w=f;var E=h,G=n,C=B.textContent?B.textContent:"",I=B.getAttribute("p");I=I?this.pens[I]:null;B=C5(B,"t")||0;y=new x5(y+B,z-B,G,w,C,E,I)}}else y=new x5(l,m,n,f,w.textContent||"",h,p);c.push(y);this.B=y}if(0<c.length)for(c[0].windowId===this.F&&(this.j=X4a(this,a,b,!0),d.push(this.j)),a=g.t(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var W5a=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(H5,A5);H5.prototype.reset=function(){this.B.clear()};
H5.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.t(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.zH=I5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=I5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=I5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.mf=10<h?h-1:h,f.Sl=W5a.get(f.mf));e.hgHorizGroup&&(f.EQ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.t(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.F.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Ow=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.uh=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.WL=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=I5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.F.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.t(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.cj=e.ahHorPos),void 0!==e.apPoint&&(f.vk=e.apPoint),void 0!==e.avVerPos&&(f.Tl=e.avVerPos),void 0!==e.ccCols&&(f.Op=e.ccCols),void 0!==e.rcRows&&(f.bp=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.t(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=Y4a(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+z5++,h=Y4a(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var r=p[l],w=r.utf8;if(w){var y=r.tOffsetMs||0,z=null;r.pPenId&&(z=this.j.get(r.pPenId));if(2===(null!=h.params.Ow?h.params.Ow:1<h.j.length?1:0)&&m&&"\n"===w)continue;if(r=z&&1===z.mf)if(r=l,r+3>=p.length||!p[r+1].pPenId||!p[r+2].pPenId||!p[r+3].pPenId)r=!1;else{var B=p[r+1].pPenId;(B=this.j.get(B))&&B.mf&&2===B.mf?(B=p[r+2].pPenId,B=this.j.get(B),!B||!B.mf||3>B.mf?r=!1:(B=p[r+3].pPenId,r=(B=this.j.get(B))&&
B.mf&&2===B.mf?!0:!1)):r=!1}if(r){y=p[l+1].utf8;r=p[l+3].utf8;B=p[l+2].utf8;var E=this.j.get(p[l+2].pPenId);w=T4a(w,y,B,r,E);m=new x5(d,e,n,f,w,m,z);l+=3}else m=new x5(d+y,e-y,n,h.id,w,m,z||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};$4a.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
$4a.prototype.reset=function(){this.mode=0;this.C.reset(0);this.F.reset(1)};
var a5a=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];J5.prototype.set=function(a){this.type=a};
J5.prototype.get=function(){return this.type};
K5.prototype.clear=function(){this.state=0};
K5.prototype.update=function(){this.state=2===this.state?1:0};
K5.prototype.isValid=function(){return 0!==this.state};
K5.prototype.matches=function(a,b){return this.isValid()&&a===this.gs&&b===this.Kp};
f5a.prototype.reset=function(){this.timestamp=this.j=0};
L5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
L5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
L5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var g5a=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],h5a=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],i5a=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],j5a=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];n5a.prototype.reset=function(a,b){this.F=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Z4a.prototype.reset=function(a){this.F=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};r5a.prototype.C=function(){};g.v(Q5,r5a);Q5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+z5++;c=c/1E3-this.I;d=d/1E3-this.I;a=new y5(c,d-c,5,f,{textAlign:0,vk:0,cj:2.5*b,Tl:5.33*a});e=new x5(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.v(T5,A5);T5.prototype.u=function(a){a=new Q5(a,a.byteLength,this.B);if(s5a(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=S5(a)*(1E3/45):1===a.version&&(a.B=4294967296*S5(a)+S5(a)),a.F=R5(a);0<a.F;a.F--){var b=R5(a),c=R5(a),d=R5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,bP:c,cP:d,order:b.j.length}))}e5a(this.j,a);return a.u}return[]};
T5.prototype.reset=function(){this.j.clear()};g.v(U5,A5);
U5.prototype.u=function(a,b){var c=[];a=a.split(X5a);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!Y5a.test(e)){var h=Z5a.exec(e);if(h&&4<=h.length){var l=v5a(h[1]),m=v5a(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,w="";n=g.t(n);for(var y=n.next();!y.done;y=n.next())if(y=y.value.split(":"),2===y.length){var z=y[1];switch(y[0]){case "line":y=z.split(",");y[0].endsWith("%")&&(p=y[0],h.Tl=Number.parseInt(p,10),2===y.length&&(q=y[1].trim()));break;case "position":y=
z.split(",");r=y[0];h.cj=Number.parseInt(r,10);2===y.length&&(w=y[1].trim());break;case "align":switch(z){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.cj=0;break;case 1:h.cj=100;break;case 2:h.cj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(w){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.vk=q}e=e.substring(Z5a.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=w5a(l,m,5,w),m=new x5(l,m,5,f.id,h,!1,g.Ef(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split($5a),1===q.length?(h=5,w=w5a(l,m,h,w)):(p=h=6,w=Object.assign({Op:32},w),w=new y5(l,m,p,"_"+z5++,w)),c.push(w),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(y=g.$Ya("<html>"+n+"</html>"),y.getElementsByTagName("parsererror").length?
(z=y.createElement("span"),z.appendChild(y.createTextNode(n))):z=y.firstChild,u5a(this,p,m-(p-l),h,w,0<r,z,e,c)):p=v5a(n)+f}Z5a.lastIndex=0}}return c};
var Y5a=/^NOTE/,X5a=/(?:\r\n|\r|\n){2,}/,Z5a=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),$5a=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.cT.DD(U5,{u:"wvppt"});g.v(V5,g.M);V5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
V5.prototype.reset=function(){this.parser&&this.parser.reset()};
V5.prototype.ra=function(){g.M.prototype.ra.call(this);this.clear()};var d6={windowColor:"#080808",windowOpacity:0,textAlign:2,vk:7,cj:50,Tl:100,isDefault:!0,Yd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(W5,g.LO);g.k=W5.prototype;g.k.ra=function(){if(this.C||this.oa){var a=this.G.Vd();a&&!a.isDisposed()&&a.Kv()}else T5a(this,!1);g.LO.prototype.ra.call(this)};
g.k.Zt=function(){if(this.Xa)return this.C||this.oa;var a=s4a(this.player.getAudioTrack(),t4a(this.Y));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?X5(this):K5a(this)||X5(this)?!0:L5a(this)};
g.k.load=function(){var a=this;g.LO.prototype.load.call(this);var b=!this.Y.N("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.u?(this.j&&(this.bb.clear(),this.C?O5a(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Fq(this.j,"json3",function(c,d,e,f){if(c){a.u.SK()&&(a.Ba=[],a.G.Af("captions"),g.ho(a.Ia),a.bb.reset());c=C5a(a.bb,c,d,e,f);a.player.le(c,void 0,a.ib);if(!(!a.ya||a.oa||$5(a)||g.vG(a.Y)||g.mG(a.Y))){g.lo(a.La);c=S4a({vk:0,cj:5,Tl:5,
bp:2,textAlign:0,uh:0,lang:"zh-CN"});a.Pa=[c];e=["\u70b9\u51fb "," \u67e5\u770b\u8bbe\u7f6e"];a.kb||(f=new g.uL(g.ML()),g.N(a,f),a.kb=f.element);f=c.end-c.start;var h=g.bH(a.j);h&&a.Pa.push(new x5(c.start,f,0,c.id,h));a.Pa.push(new x5(c.start,f,0,c.id,e[0]),new x5(c.start,f,0,c.id,a.kb,!0),new x5(c.start,f,0,c.id,e[1],!0));a.player.le(a.Pa);g.jo(a.La)}!a.ya||a.oa||$5(a)||(g.JG(a.Y)?b6(a,!0):c6(a,"module-enabled",!0),a.I&&(a.I.C=a.j),a.player.pu());var l;null==(l=a.G.Jc())||l.va("cc",{kind:d.kind});
a.ya=!1}}),!b||this.C||this.oa||$5(this)||this.player.Oa("captionschanged",g.cH(this.j))),b||(this.j&&!$5(this)?this.player.Oa("captionschanged",g.cH(this.j)):this.player.Oa("onCaptionsTrackListChanged"))):(this.u=M5a(this),g.N(this,this.u),this.u.Kw(function(){N5a(a)}))};
g.k.unload=function(){this.C&&this.j?O5a(this,!1):(this.La&&g.lo(this.La),this.player.Af("captions"),this.Ba=[],this.u&&this.u.rp(),this.bb.clear(),this.J&&this.player.le(this.J),this.tM());g.LO.prototype.unload.call(this);this.player.pu();this.player.Oa("captionschanged",{})};
g.k.create=function(){this.Zt()&&this.load()};
g.k.v4=function(){for(var a=this.G.Vd().Cf().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.MO(this.u.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.j:null)!==b&&a6(this,b,!0)};
g.k.j7=function(){!this.j&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ba.push(a);g.ho(this.Ia)};
g.k.onCueRangeExit=function(a){g.fc(this.Ba,a);this.u instanceof s5&&this.u.I&&this.player.qh([a]);g.ho(this.Ia)};
g.k.getCaptionWindowContainerId=function(){return this.ea.element.id};
g.k.q5=function(){S5a(this,this.Pa);this.Pa=null};
g.k.qM=function(){var a=this;if(!this.Ob||!this.C){this.Ia.stop();g.Dca(this.Sa);this.Ba.sort(g.BA);var b=this.Ba;if(this.J){var c=g.Dm(b,function(f){return-1===this.J.indexOf(f)},this);
c.length&&(b=c)}b=g.t(b);for(c=b.next();!c.done;c=b.next())Q5a(this,c.value);b={};c=g.t(Object.entries(this.Z));for(var d=c.next();!d.done;b={Hr:b.Hr,jl:b.jl},d=c.next()){var e=g.t(d.value);d=e.next().value;e=e.next().value;b.Hr=d;b.jl=e;this.Sa[b.Hr]?(b.jl.element.parentNode||(b.jl instanceof w5||b.jl instanceof v5||g.qf(this.Z,function(f){return function(h,l){l!==f.Hr&&h.u.params.vk===f.jl.u.params.vk&&h.u.params.cj===f.jl.u.params.cj&&h.u.params.Tl===f.jl.u.params.Tl&&(h.dispose(),delete a.Z[l]);
return l===f.Hr}}(b),this),R5a(this,b.jl.element)),b.jl.wx(this.Sa[b.Hr])):(b.jl.dispose(),delete this.Z[b.Hr])}}};
g.k.w5=function(){G5a(this,{},!0);this.Y.N("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Oa("captionssettingschanged")};
g.k.p_=function(){var a=d6.Yd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:d6.windowColor,windowOpacity:d6.windowOpacity};var b=H5a(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.sU=function(a,b){var c={};Object.assign(c,H5a(this));Object.assign(c,a);G5a(this,c,b);this.player.Oa("captionssettingschanged")};
g.k.tM=function(){!this.C&&this.loaded&&(g.nf(this.Z,function(a,b){a.dispose();delete this.Z[b]},this),this.qM())};
g.k.Fg=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Jg(b,-2,4);this.sU({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&a6(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.Y.F&&(g.JG(this.Y)?b6(this,!!b):c6(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Ma(b))break;if(g.Ef(b)){a6(this,null,!0);break}a=g.MO(this.u.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?v4a(e,b.translationLanguage):e)}U5a(this,b.position);!c||c===this.j&&this.loaded||(b=g.tya(),a=g.dH(c),b.length&&a===b[b.length-1]||(b.push(a),g.Xz("yt-player-caption-language-preferences",b)),u4a(this.Y)&&!this.G.isInline()&&g.Xz("yt-player-caption-sticky-language",a),a6(this,c,!0))}else return this.loaded&&this.j&&!$5(this)?g.cH(this.j):{};return"";case "tracklist":return this.u?g.Wk(g.MO(this.u.j,!(!b||!b.includeAsr)),function(f){return g.cH(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||T5a(this,!!b);break;case "sampleSubtitlesCustomized":this.C||T5a(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.F&&a.push("stickyLoading");return a};
g.k.MI=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.Y.N("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.dH(a));return{cc:b}}return{}};
g.k.O6=function(){this.loaded&&this.j&&!$5(this)?(g.JG(this.Y)?b6(this,!1):c6(this,"module-enabled",!1),this.unload(),X5(this,!0)&&a6(this,Y5(this),!1)):this.VT()};
g.k.VT=function(){this.loaded&&this.j&&!$5(this)||a6(this,$5(this)||!this.j?Z5(this,!0):this.j,!0)};
g.k.X1=function(){var a=$5(this);X5(this,a)?a6(this,this.player.getAudioTrack().u,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Zt()&&(a?a6(this,Z5(this),!1):this.load()))};
g.k.R2=function(){var a=this.G.Vd();a&&!a.isDisposed()&&a.Kv();this.G.isFullscreen()?(this.C=this.Xa=!0,this.loaded&&N5a(this)):(this.Xa="3"===this.Y.controlsType,this.C=F5a(this));a6(this,this.j)};
g.cT.DD(W5,{qM:"smucd"});g.KO("captions",W5);})(_yt_player);
